Update 02-manual-trigger-job.yml

diff --git a/.github/workflows/02-manual-trigger-job.yml b/.github/workflows/02-manual-trigger-job.yml
--- a/.github/workflows/02-manual-trigger-job.yml
+++ b/.github/workflows/02-manual-trigger-job.yml
@@ -9,16 +9,29 @@ jobs:
     steps:
     - name: Check out repo
       uses: actions/checkout@main
-    - name: Directory oath 
-      run: |
-        cd /home/runner/work/Azure-MLops/src
-        pwd
-    - name: Install az ml extension
-      run: az extension add -n ml -y
     - name: Azure login
       uses: azure/login@v1
       with:
         creds: ${{secrets.AZURE_CREDENTIALS}}
-    - name: Create run
-      run: az ml job create --file job.yml --workspace-name aml-pipelinecli-dev --resource-group mlops-pipelinecli-rg
-
+    - name: setup
+      run: bash setup.sh
+      working-directory: src
+      continue-on-error: true
+    - name: create job
+      run: |
+        run_id=$(az ml job create -f job.yml --query name -o tsv)
+        az ml job stream -n $run_id
+        status=$(az ml job show -n $run_id --query status -o tsv)
+        echo $status
+        if [[ $status == "Completed" ]]
+        then
+          echo "Job completed"
+        elif [[ $status ==  "Failed" ]]
+        then
+          echo "Job failed"
+          exit 1
+        else 
+          echo "Job status not failed or completed"
+          exit 2
+        fi
+      working-directory: src
